### ISSUE TITLE
Wiki 错误 

### ISSUE THREAD

**Issue by sigma18** [iqiyi/LiteApp#1]
1. 格式错误 https://github.com/iqiyi/LiteApp/wiki/android-native-interface

2. 链接错误 Android Page data
http://gitlab.qiyi.domain/cross-team/lite-app/wikis/android-%E7%BB%84%E4%BB%B6-page_data

3. 链接错误
web introduction 页面中的链接均有误

**Comment by zhch0633** [comment]
感谢反馈，wiki 搬运修复中

**Comment by zhch0633** [comment]
fixed thanks, and also want some to join us
