### ISSUE TITLE
初始化的一些疑问

### ISSUE THREAD

**Issue by 70kg** [iqiyi/LiteApp#10]
1. `https://locahost:8080/pages/${bundleName}/web.html`
这里的bundleName是指什么？
2. `public static void startMiniProgram(String miniProgramID, boolean needUpdate, Activity context)
`
这个方法在哪调用？在Android的sdk中找不到？
谢谢

**Comment by zhch0633** [comment]
2、文档有误，马上修改，请使用
LiteAppHelper.startLiteAppPackage(LiteAppListActivity.this, item.getId(),true, initData,false);
具体用法可以参考我们的demo，谢谢
