### ISSUE TITLE
Demo application is incomplete

### ISSUE THREAD

**Issue by zairl23** [iqiyi/LiteApp#3]
In https://github.com/iqiyi/LiteApp/tree/master/FE/demo/hello-world, i found the src directory is ignored, could you add src content?

**Comment by pricelesss** [comment]
Fixed now , thanks !

**Comment by zairl23** [comment]
Thanks! [The iqiyi demo](https://github.com/iqiyi/LiteApp/tree/master/FE/demo/iqiyi)) is also incomplete

**Comment by pricelesss** [comment]
there is some private code in "iqiyi" demo so that "src" dir can not be public , so sorry about that...
