### ISSUE TITLE
npm i --save @iqiyi/liteapp-base@0.0.1 @iqiyi/liteapp-cli@^0.0.1

### ISSUE THREAD

**Issue by airbloodrain** [iqiyi/LiteApp#4]
this command throws error 404,how can i resume it

**Comment by pricelesss** [comment]
It's the error in wiki : ( 
> https://github.com/iqiyi/LiteApp/wiki/web-Getting-Started

now the command has been updated to
```javascript
npm i --save liteapp-base@0.0.1 liteapp-cli@^0.0.1
```
refer to the hello-world project in demo
> https://github.com/iqiyi/LiteApp/tree/master/FE/demo/hello-world

we'll add the init command ( like lite-app init ) to liteapp-cli to make the installation simpler

thank u for your help ! good luck !
